const createdAt = '2026-03-21T08:00:00Z';

const seedData = {
  users: [
    {
      id: 'user-daniel',
      githubId: 1111,
      telegramId: null,
      email: 'daniel@skillhub.dev',
      username: 'danieltgrm',
      avatarUrl: 'https://avatars.githubusercontent.com/u/1?v=4',
      displayName: 'Даниэл Петров',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-denis',
      githubId: 2222,
      telegramId: null,
      email: 'denis@skillhub.dev',
      username: 'denisui',
      avatarUrl: 'https://avatars.githubusercontent.com/u/2?v=4',
      displayName: 'Денис Соколов',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-deni',
      githubId: 3333,
      telegramId: null,
      email: 'deni@skillhub.dev',
      username: 'deniops',
      avatarUrl: 'https://avatars.githubusercontent.com/u/3?v=4',
      displayName: 'Дени Алиев',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-captain',
      githubId: 4444,
      telegramId: null,
      email: 'captain@skillhub.dev',
      username: 'captainpro',
      avatarUrl: 'https://avatars.githubusercontent.com/u/4?v=4',
      displayName: 'Артем Капустин',
      isPro: true,
      proExpiresAt: '2026-04-21T08:00:00Z',
      userRole: 'captain',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-aida',
      githubId: 5551,
      telegramId: null,
      email: 'aida@skillhub.dev',
      username: 'aidafront',
      avatarUrl: 'https://avatars.githubusercontent.com/u/5?v=4',
      displayName: 'Аида Смагулова',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-nikita',
      githubId: 5552,
      telegramId: null,
      email: 'nikita@skillhub.dev',
      username: 'nikitaback',
      avatarUrl: 'https://avatars.githubusercontent.com/u/6?v=4',
      displayName: 'Никита Белов',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-lera',
      githubId: 5553,
      telegramId: null,
      email: 'lera@skillhub.dev',
      username: 'lerafull',
      avatarUrl: 'https://avatars.githubusercontent.com/u/7?v=4',
      displayName: 'Лера Волкова',
      isPro: true,
      proExpiresAt: '2026-05-10T08:00:00Z',
      userRole: 'both',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-maks',
      githubId: 5554,
      telegramId: null,
      email: 'maks@skillhub.dev',
      username: 'maksdesign',
      avatarUrl: 'https://avatars.githubusercontent.com/u/8?v=4',
      displayName: 'Макс Иманов',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-artem',
      githubId: 5555,
      telegramId: null,
      email: 'artem@skillhub.dev',
      username: 'artemml',
      avatarUrl: 'https://avatars.githubusercontent.com/u/9?v=4',
      displayName: 'Артем Гуляев',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-sofia',
      githubId: 5556,
      telegramId: null,
      email: 'sofia@skillhub.dev',
      username: 'sofiamobile',
      avatarUrl: 'https://avatars.githubusercontent.com/u/10?v=4',
      displayName: 'София Каримова',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-roman',
      githubId: 5557,
      telegramId: null,
      email: 'roman@skillhub.dev',
      username: 'romanother',
      avatarUrl: 'https://avatars.githubusercontent.com/u/11?v=4',
      displayName: 'Роман Ежов',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-alina',
      githubId: 5558,
      telegramId: null,
      email: 'alina@skillhub.dev',
      username: 'alinaui',
      avatarUrl: 'https://avatars.githubusercontent.com/u/12?v=4',
      displayName: 'Алина Темирова',
      isPro: true,
      proExpiresAt: '2026-07-01T08:00:00Z',
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-timur',
      githubId: 5559,
      telegramId: null,
      email: 'timur@skillhub.dev',
      username: 'timurdb',
      avatarUrl: 'https://avatars.githubusercontent.com/u/13?v=4',
      displayName: 'Тимур Айтбаев',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-olga',
      githubId: 5560,
      telegramId: null,
      email: 'olga@skillhub.dev',
      username: 'olgapm',
      avatarUrl: 'https://avatars.githubusercontent.com/u/14?v=4',
      displayName: 'Ольга Самойлова',
      isPro: false,
      proExpiresAt: null,
      userRole: 'both',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-ivan',
      githubId: 5561,
      telegramId: null,
      email: 'ivan@skillhub.dev',
      username: 'ivansre',
      avatarUrl: 'https://avatars.githubusercontent.com/u/15?v=4',
      displayName: 'Иван Коваленко',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: 'user-zara',
      githubId: 5562,
      telegramId: null,
      email: 'zara@skillhub.dev',
      username: 'zaradata',
      avatarUrl: 'https://avatars.githubusercontent.com/u/16?v=4',
      displayName: 'Зара Исхакова',
      isPro: false,
      proExpiresAt: null,
      userRole: 'participant',
      createdAt,
      updatedAt: createdAt,
    },
  ],
  profiles: [
    {
      id: 'profile-daniel', userId: 'user-daniel', role: 'backend', claimedGrade: 'middle',
      primaryStack: ['Node.js', 'PostgreSQL', 'Express'], experienceYears: 2, hackathonsCount: 3,
      bio: 'Backend-разработчик, люблю API и структуру.',
      projectLinks: [{ url: 'https://github.com/daniel/project', title: 'Hackathon API', description: 'Demo REST API for team matching.' }],
      telegramUsername: 'danieltgrm', githubUrl: 'https://github.com/daniel', isPublic: true,
      githubData: { fetchedAt: createdAt, publicRepos: 8, followers: 3, accountAgeYears: 3, languages: { JavaScript: 32000, TypeScript: 12000, SQL: 4000 }, topRepos: [] },
      lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-denis', userId: 'user-denis', role: 'frontend', claimedGrade: 'middle',
      primaryStack: ['React', 'TypeScript', 'Tailwind'], experienceYears: 2, hackathonsCount: 2,
      bio: 'Frontend и продуктовые интерфейсы.', projectLinks: [], telegramUsername: 'denisui', githubUrl: 'https://github.com/denis',
      githubData: { fetchedAt: createdAt, publicRepos: 6, followers: 4, accountAgeYears: 2, languages: { TypeScript: 28000, JavaScript: 18000, CSS: 8000 }, topRepos: [] },
      isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-deni', userId: 'user-deni', role: 'design', claimedGrade: 'junior',
      primaryStack: ['Figma', 'Design Systems'], experienceYears: 1, hackathonsCount: 1,
      bio: 'Делаю интерфейсы и презентации.', projectLinks: [], telegramUsername: 'deniops', githubUrl: 'https://github.com/deni',
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-captain', userId: 'user-captain', role: 'backend', claimedGrade: 'senior',
      primaryStack: ['Node.js', 'PostgreSQL', 'Redis'], experienceYears: 6, hackathonsCount: 9,
      bio: 'Капитан и backend lead.', projectLinks: [], telegramUsername: 'captainpro', githubUrl: 'https://github.com/captain',
      githubData: { fetchedAt: createdAt, publicRepos: 42, followers: 120, accountAgeYears: 7, languages: { TypeScript: 160000, JavaScript: 95000, SQL: 34000, Python: 27000 }, topRepos: [] },
      isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-aida', userId: 'user-aida', role: 'frontend', claimedGrade: 'junior',
      primaryStack: ['React', 'JavaScript', 'CSS'], experienceYears: 0, hackathonsCount: 1,
      bio: 'Делаю лендинги и UI-компоненты.', projectLinks: [], telegramUsername: 'aidafront', githubUrl: null,
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-nikita', userId: 'user-nikita', role: 'backend', claimedGrade: 'middle',
      primaryStack: ['Node.js', 'PostgreSQL', 'Kafka'], experienceYears: 3, hackathonsCount: 4,
      bio: 'API, очереди и интеграции.', projectLinks: [], telegramUsername: 'nikitaback', githubUrl: 'https://github.com/nikita',
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-lera', userId: 'user-lera', role: 'fullstack', claimedGrade: 'senior',
      primaryStack: ['TypeScript', 'React', 'Node.js'], experienceYears: 5, hackathonsCount: 7,
      bio: 'Fullstack lead, веду продукт от идеи до продакшна.', projectLinks: [], telegramUsername: 'lerafull', githubUrl: 'https://github.com/lera',
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-maks', userId: 'user-maks', role: 'design', claimedGrade: 'middle',
      primaryStack: ['Figma', 'UX Research', 'Design System'], experienceYears: 3, hackathonsCount: 5,
      bio: 'Продуктовый дизайнер с упором на UX.', projectLinks: [], telegramUsername: 'maksdesign', githubUrl: null,
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-artem', userId: 'user-artem', role: 'ml', claimedGrade: 'middle',
      primaryStack: ['Python', 'PyTorch', 'FastAPI'], experienceYears: 2, hackathonsCount: 3,
      bio: 'ML-инженер: прототипы, модели и инференс.', projectLinks: [], telegramUsername: 'artemml', githubUrl: 'https://github.com/artem',
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-sofia', userId: 'user-sofia', role: 'mobile', claimedGrade: 'middle',
      primaryStack: ['Flutter', 'Dart', 'Firebase'], experienceYears: 2, hackathonsCount: 4,
      bio: 'Кроссплатформенная мобильная разработка.', projectLinks: [], telegramUsername: 'sofiamobile', githubUrl: null,
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-roman', userId: 'user-roman', role: 'other', claimedGrade: 'junior',
      primaryStack: ['Product', 'No-code', 'Automation'], experienceYears: 1, hackathonsCount: 2,
      bio: 'Product/ops роль, быстро собираю MVP.', projectLinks: [], telegramUsername: 'romanother', githubUrl: null,
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-alina', userId: 'user-alina', role: 'frontend', claimedGrade: 'senior',
      primaryStack: ['React', 'Next.js', 'TypeScript'], experienceYears: 6, hackathonsCount: 8,
      bio: 'Frontend архитектор, сложные SPA и DX.', projectLinks: [], telegramUsername: 'alinaui', githubUrl: 'https://github.com/alina',
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-timur', userId: 'user-timur', role: 'backend', claimedGrade: 'junior',
      primaryStack: ['Go', 'PostgreSQL', 'Redis'], experienceYears: 1, hackathonsCount: 1,
      bio: 'Изучаю backend и инфраструктуру.', projectLinks: [], telegramUsername: 'timurdb', githubUrl: null,
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-olga', userId: 'user-olga', role: 'fullstack', claimedGrade: 'middle',
      primaryStack: ['Vue', 'Node.js', 'MongoDB'], experienceYears: 3, hackathonsCount: 5,
      bio: 'Fullstack с фокусом на MVP и интеграции.', projectLinks: [], telegramUsername: 'olgapm', githubUrl: 'https://github.com/olga',
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-ivan', userId: 'user-ivan', role: 'backend', claimedGrade: 'middle',
      primaryStack: ['Kubernetes', 'Node.js', 'PostgreSQL'], experienceYears: 4, hackathonsCount: 6,
      bio: 'SRE + backend, надежность и мониторинг.', projectLinks: [], telegramUsername: 'ivansre', githubUrl: null,
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
    {
      id: 'profile-zara', userId: 'user-zara', role: 'ml', claimedGrade: 'senior',
      primaryStack: ['Python', 'TensorFlow', 'MLOps'], experienceYears: 5, hackathonsCount: 7,
      bio: 'Data/ML lead, production-ready pipelines.', projectLinks: [], telegramUsername: 'zaradata', githubUrl: 'https://github.com/zara',
      githubData: null, isPublic: true, lastScoredAt: null, createdAt, updatedAt: createdAt,
    },
  ],
  ratings: [
    { id: 'rating-daniel', profileId: 'profile-daniel', score: 82, grade: 'Middle Backend', roleLabel: 'Backend', strengths: ['Сильный backend-стек'], improvements: ['Добавить тесты'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-denis', profileId: 'profile-denis', score: 76, grade: 'Middle Frontend', roleLabel: 'Frontend', strengths: ['Современный frontend stack'], improvements: ['Усилить системный дизайн'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-deni', profileId: 'profile-deni', score: 64, grade: 'Junior Design', roleLabel: 'Design', strengths: ['Понимает визуальную композицию'], improvements: ['Больше практики в продуктовых сценариях'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-captain', profileId: 'profile-captain', score: 92, grade: 'Senior Backend', roleLabel: 'Backend', strengths: ['Сильная архитектура'], improvements: ['Упростить часть решений для MVP'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-aida', profileId: 'profile-aida', score: 49, grade: 'Junior Frontend', roleLabel: 'Frontend', strengths: ['Базовый UI-stack'], improvements: ['Добавить проекты'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-nikita', profileId: 'profile-nikita', score: 78, grade: 'Middle Backend', roleLabel: 'Backend', strengths: ['Сервисная архитектура'], improvements: ['Усилить observability'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-lera', profileId: 'profile-lera', score: 90, grade: 'Senior Fullstack', roleLabel: 'Fullstack', strengths: ['Сильный fullstack опыт'], improvements: ['Больше фокуса на perf'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-maks', profileId: 'profile-maks', score: 72, grade: 'Middle Design', roleLabel: 'Design', strengths: ['UX-исследования'], improvements: ['Добавить case studies'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-artem', profileId: 'profile-artem', score: 74, grade: 'Middle ML', roleLabel: 'Ml', strengths: ['ML prototyping'], improvements: ['Усилить MLOps'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-sofia', profileId: 'profile-sofia', score: 70, grade: 'Middle Mobile', roleLabel: 'Mobile', strengths: ['Стабильные mobile релизы'], improvements: ['Усилить testing'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-roman', profileId: 'profile-roman', score: 45, grade: 'Junior Other', roleLabel: 'Other', strengths: ['Быстрые MVP'], improvements: ['Подтянуть тех. базу'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-alina', profileId: 'profile-alina', score: 88, grade: 'Senior Frontend', roleLabel: 'Frontend', strengths: ['Архитектура UI'], improvements: ['Делегирование'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-timur', profileId: 'profile-timur', score: 53, grade: 'Junior Backend', roleLabel: 'Backend', strengths: ['База по Go и SQL'], improvements: ['Проектная практика'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-olga', profileId: 'profile-olga', score: 79, grade: 'Middle Fullstack', roleLabel: 'Fullstack', strengths: ['Быстрый delivery'], improvements: ['Глубже в backend perf'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-ivan', profileId: 'profile-ivan', score: 84, grade: 'Middle Backend', roleLabel: 'Backend', strengths: ['Надежность и мониторинг'], improvements: ['Документация'], rawResponse: { source: 'seed' }, createdAt },
    { id: 'rating-zara', profileId: 'profile-zara', score: 91, grade: 'Senior ML', roleLabel: 'Ml', strengths: ['Production ML pipelines'], improvements: ['Больше mentoring'], rawResponse: { source: 'seed' }, createdAt },
  ],
  teams: [
    {
      id: 'team-viribus',
      authorId: 'user-captain',
      name: 'Viribus Matchers',
      description: 'Ищем backend и дизайнера для хакатона.',
      hackathonName: 'Viribus Hackathon',
      requiredRoles: ['backend', 'design'],
      minRating: 70,
      stack: ['Node.js', 'React'],
      slotsOpen: 2,
      isActive: true,
      status: 'active',
      updatedAt: createdAt,
      deletedAt: null,
      createdAt,
    },
    {
      id: 'team-ai-hub',
      authorId: 'user-daniel',
      name: 'AI Hub',
      description: 'Собираем команду вокруг AI-демо.',
      hackathonName: 'Viribus Hackathon',
      requiredRoles: ['frontend', 'backend'],
      minRating: 60,
      stack: ['TypeScript', 'React'],
      slotsOpen: 1,
      isActive: true,
      status: 'active',
      updatedAt: createdAt,
      deletedAt: null,
      createdAt,
    },
    {
      id: 'team-mobile-fusion',
      authorId: 'user-sofia',
      name: 'Mobile Fusion',
      description: 'Ищем ML и backend для мобильного AI ассистента.',
      hackathonName: 'Viribus Hackathon',
      requiredRoles: ['ml', 'backend'],
      minRating: 65,
      stack: ['Flutter', 'Python', 'PostgreSQL'],
      slotsOpen: 2,
      isActive: true,
      status: 'active',
      updatedAt: createdAt,
      deletedAt: null,
      createdAt,
    },
  ],
  teamMembers: [
    { id: 'member-captain', teamId: 'team-viribus', userId: 'user-captain', role: 'backend', joinedAt: createdAt },
    { id: 'member-daniel', teamId: 'team-ai-hub', userId: 'user-daniel', role: 'backend', joinedAt: createdAt },
    { id: 'member-sofia', teamId: 'team-mobile-fusion', userId: 'user-sofia', role: 'mobile', joinedAt: createdAt },
  ],
  applications: [
    {
      id: 'app-denis-viribus',
      applicantId: 'user-denis',
      teamId: 'team-viribus',
      message: 'Хочу сделать фронтенд и забрать UX.',
      status: 'pending',
      viewedAt: null,
      updatedAt: createdAt,
      createdAt,
    },
    {
      id: 'app-artem-mobile',
      applicantId: 'user-artem',
      teamId: 'team-mobile-fusion',
      message: 'Могу закрыть ML и inference часть.',
      status: 'pending',
      viewedAt: null,
      updatedAt: createdAt,
      createdAt,
    },
  ],
};

function summarizeSeed(data) {
  const roles = Array.from(new Set(data.profiles.map((item) => item.role))).sort();
  const scores = data.ratings.map((item) => item.score);
  const minScore = Math.min(...scores);
  const maxScore = Math.max(...scores);

  return {
    users: data.users.length,
    profiles: data.profiles.length,
    ratings: data.ratings.length,
    roles,
    minScore,
    maxScore,
  };
}

if (require.main === module) {
  const summary = summarizeSeed(seedData);
  console.log('Seed dataset is ready.');
  console.log(JSON.stringify(summary, null, 2));
}

module.exports = { seedData, summarizeSeed };
